server.port=9090

spring.application.name=stats-server
spring.datasource.url=${STATS_DB_URL:jdbc:postgresql://localhost:5432/ewm_stats}
spring.datasource.username=${STATS_DB_USER:stats}
spring.datasource.password=${STATS_DB_PASSWORD:stats}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info
