server.port=8080

spring.datasource.url=${MAIN_DB_URL:jdbc:postgresql://localhost:5432/ewm_main}
spring.datasource.username=${MAIN_DB_USER:main}
spring.datasource.password=${MAIN_DB_PASSWORD:main}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.sql.init.mode=always

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}
